package org.rynk.keyboard

/** Keyboard languages offered in the settings: code (as understood by the engine) and name. */
object KeyboardLanguages {
    val all = listOf(
        "ru" to "Русский (Russian)",
        "en" to "English",
        "de" to "Deutsch (German)",
        "fr" to "Français (French)",
        "es" to "Español (Spanish)",
        "pt" to "Português (Portuguese)",
        "it" to "Italiano (Italian)",
        "tr" to "Türkçe (Turkish)",
        "uk" to "Українська (Ukrainian)",
        "be" to "Беларуская (Belarusian)",
        "kk" to "Қазақша (Kazakh)",
        "ar" to "العربية (Arabic)",
        "pl" to "Polski (Polish)",
        "cs" to "Čeština (Czech)",
        "ro" to "Română (Romanian)",
        "nl" to "Nederlands (Dutch)",
        "sv" to "Svenska (Swedish)",
        "no" to "Norsk (Norwegian)",
        "da" to "Dansk (Danish)",
        "fi" to "Suomi (Finnish)",
        "el" to "Ελληνικά (Greek)",
        "he" to "עברית (Hebrew)",
        "fa" to "فارسی (Persian)",
        "ur" to "اردو (Urdu)",
        "hi" to "हिन्दी (Hindi)",
        "bn" to "বাংলা (Bengali)",
        "id" to "Bahasa Indonesia (Indonesian)",
        "ms" to "Bahasa Melayu (Malay)",
        "vi" to "Tiếng Việt (Vietnamese)",
        "th" to "ไทย (Thai)",
        "hu" to "Magyar (Hungarian)",
        "bg" to "Български (Bulgarian)",
        "sr" to "Српски (Serbian)",
        "hr" to "Hrvatski (Croatian)",
        "sk" to "Slovenčina (Slovak)",
        "sl" to "Slovenščina (Slovenian)",
        "lt" to "Lietuvių (Lithuanian)",
        "lv" to "Latviešu (Latvian)",
        "et" to "Eesti (Estonian)",
        "ka" to "ქართული (Georgian)",
        "hy" to "Հայերեն (Armenian)",
        "az" to "Azərbaycan (Azerbaijani)",
        "uz" to "Oʻzbekcha (Uzbek)",
        "tg" to "Тоҷикӣ (Tajik)",
        "ky" to "Кыргызча (Kyrgyz)",
        "tk" to "Türkmençe (Turkmen)",
        "mn" to "Монгол (Mongolian)",
        "tl" to "Tagalog (Filipino)",
        "sq" to "Shqip (Albanian)",
        "bs" to "Bosanski (Bosnian)",
        "mk" to "Македонски (Macedonian)",
        "is" to "Íslenska (Icelandic)",
        "ga" to "Gaeilge (Irish)",
        "cy" to "Cymraeg (Welsh)",
        "eu" to "Euskara (Basque)",
        "ca" to "Català (Catalan)",
        "gl" to "Galego (Galician)",
        "af" to "Afrikaans",
        "sw" to "Kiswahili (Swahili)",
        "ha" to "Hausa",
        "yo" to "Yorùbá (Yoruba)",
        "ig" to "Igbo",
        "zu" to "isiZulu (Zulu)",
        "eo" to "Esperanto",
        "la" to "Latina (Latin)",
        "ta" to "தமிழ் (Tamil)",
        "te" to "తెలుగు (Telugu)",
        "mr" to "मराठी (Marathi)",
        "gu" to "ગુજરાતી (Gujarati)",
        "kn" to "ಕನ್ನಡ (Kannada)",
        "ml" to "മലയാളം (Malayalam)",
        "pa" to "ਪੰਜਾਬੀ (Punjabi)",
        "ne" to "नेपाली (Nepali)",
        "si" to "සිංහල (Sinhala)",
        "my" to "မြန်မာ (Burmese)",
        "km" to "ភាសាខ្មែរ (Khmer)",
        "am" to "አማርኛ (Amharic)",
        "so" to "Soomaali (Somali)",
        "ku" to "Kurdî (Kurdish)",
        "mt" to "Malti (Maltese)",
        "ko" to "한국어 (Korean)",
        "ja" to "日本語 (Japanese)",
        "zh_cn" to "中文 简体 (Chinese Simplified)",
        "zh_tw" to "中文 繁體 (Chinese Traditional)",
        "zh_hk" to "粵語 香港 (Cantonese)"
    )

    fun name(code: String): String = all.firstOrNull { it.first == code }?.second ?: code
}
